### PR TITLE
Remove isdigit macro redefs, replace with OMR_ISDIGIT

### PR DESCRIPTION
**Pull request by Deigue**
Changes here remove the redefinition of isdigit() in
the a2e ctype.h headers. In order to fully make this
work functionally, the references/usages of isdigit()
are replaced with OMR_ISDIGIT to properly recognize
ascii digit literals. This is done by conditionally
using __isdigit_a() on z/OS platforms.

---

This is the cleaned-up changes from https://github.com/eclipse-omr/omr/pull/7413 (for historical related comments)

### CODE REVIEW

**Comment by Deigue** [comment]
@keithc-ca I unintentionally closed https://github.com/eclipse-omr/omr/pull/7413 due to a force push earlier. Don't think I could reopen that, so I created this with the cleaned up suggestions.

I verified the advice by the cpp-team and made the replacements across omr and openj9, and also tested with both XLC and Open XL compilation and confirmed that this builds with the jdk21 zos with no issues for both.

The corresponding changes for OpenJ9 are here: https://github.com/eclipse-openj9/openj9/pull/21555
Which might need to be merged at the same time as this one.

@babsingh Tagging for review/additional feedback, updates from https://github.com/eclipse-omr/omr/pull/7413

File: compiler/control/OMROptions.cpp [hunk 1]
```diff
@@ -1376,7 +1378,7 @@ OMR::Options::getNumericValue(const char *& option)
    while (pendingOperation)
       {
       int64_t current = 0;
-      while (isdigit(*option))
+      while (__isdigit_a(*option))
```
Comment (keithc-ca) [inline compiler/control/OMROptions.cpp:1381]: I don't think it's reasonable to define `_AE_BIMODAL` on all platforms, nor is it reasonable to assume that `__isdigit_a()` exists on all platforms.

I suggest we should introduce helper macros (e.g. `omr_isdigit()`) which would be suitably defined for each platform and uses of `isdigit()` would be replaced by uses of `omr_isdigit()`. The same approach should be applied for `toupper()`, `tolower()`, etc.

**Review by keithc-ca — CHANGES_REQUESTED** [review]

File: compiler/control/OMROptions.cpp (hunk 1 above)
Comment (Deigue) [reply compiler/control/OMROptions.cpp:1381]: Sounds good, I can define that in `util/a2e/headers/ctype.h` I guess.
Is there a `__tolower_a()` and `__toupper_a()` similarly available as well? Not able to find documentation around it.

Comment (keithc-ca) [reply compiler/control/OMROptions.cpp:1381]: No. `omr_isdigit()` would be defined in some OMR header file (perhaps after including `ctype.h`).

File: compiler/control/OMROptions.cpp [hunk 2]
```diff
@@ -4390,10 +4390,10 @@ OMR::Options::setCounts()
          {
          while (s[0] == ' ')
             ++s;
-         if (isdigit(s[0]))
+         if (OMR_ISDIGIT(s[0]))
             {
             count[i] = atoi(s);
-            while(isdigit(s[0]))
+            while(OMR_ISDIGIT(s[0]))
```
Comment (keithc-ca) [inline compiler/control/OMROptions.cpp:4396]: While you're here, please add the missing space after `while`; see also lines 4421, 4444 and changes in other files.

File: ddr/include/ddr/std/sstream.hpp [hunk 3]
```diff
@@ -25,18 +25,8 @@
...
-#include <sstream>
-
-#define toupper(c)     (islower(c) ? (c & _XUPPER_ASCII) : c)
-#define tolower(c)     (isupper(c) ? (c | _XLOWER_ASCII) : c)
-
-#else /* defined(J9ZOS390) */
-#include <sstream>
 #endif /* defined(J9ZOS390) */
 
+#include <sstream>
```
Comment (keithc-ca) [inline ddr/include/ddr/std/sstream.hpp:31]: This was previously not included on z/OS: Have you verified that it is now safe to include?

File: include_core/omrcomp.h [hunk 4]
```diff
@@ -23,6 +23,8 @@
 #ifndef OMRCOMP_H
 #define OMRCOMP_H
 
+#define _AE_BIMODAL
```
Comment (keithc-ca) [inline include_core/omrcomp.h:26]: I think this should be conditional:
```c
#if defined(J9ZOS390)
#define _AE_BIMODAL
#endif /* defined(J9ZOS390) */
```

**Comment by keithc-ca** [comment]
The summary and description should be updated to reflect the new plan.

File: ddr/include/ddr/std/sstream.hpp (hunk 3 above)
Comment (Deigue) [reply ddr/include/ddr/std/sstream.hpp:31]: In the before code, I am seeing `#include <sstream>` in the `J9ZOS390` clause already, inbetween the undef and defines.

That being said, it seems to be safe to include so far while compiling as well.

Comment (keithc-ca) [reply ddr/include/ddr/std/sstream.hpp:31]: Sorry, I misread the change. You are correct, `sstream` was included on all platforms before and should continue to be.

**Comment by keithc-ca** [comment]
> looks like `#define AE_BIMODAL` might have to be in each file referencing `OMR_ISDIGIT()` , does that sound right?

No, that doesn't sound right: That should be contained to the header file that defines `OMR_ISDIGIT()`.

**Comment by Deigue** [comment]
Strange ... I am trying to remove the `#if defined(J9ZOS390)` in `omrcomp.h` surrounding the `AE_BIMODAL` definition to see if it helps, but it would not make sense that part is not working as expected, while the conditional is working around pathing towards and picking the `__isdigit_a()` call later in that same file.

If that doesn't work either, then not sure why `error: use of undeclared identifier '__isdigit_a'` (i.e. isdigit_a() remains undefined) , and will ask around to the compiler team for clarification with the pr changes context.

**Comment by Deigue** [comment]
I was able to fix all the compilation problems now, with your recommended suggestions intact.

I was getting the errors from https://github.com/eclipse-omr/omr/pull/7711#issuecomment-2806830333 for every single file after moving the `AE_BIMODAL` definition, and kept testing in isolation with the full command.
It seems that having moved the `AE_BIMODAL` define into the `omrcomp.h`, it has to be explicitly defined before any direct/indirect inclusion of `ctype.h` , so that it knows to include the `isdigit_a()` definition.

Ensuring the `omrcomp.h` is included first solves the issues, and everything compiles correctly now.

File: fvtest/omrGtestGlue/omrTest.h [hunk 5]
```diff
@@ -37,17 +37,9 @@ static int iconv_init_static_variable = iconv_initialization();
  * So we explicitly include <ctype.h> and undefine the macros for gtest, after gtest we then define back the macros.
  */
```
Comment (keithc-ca) [inline fvtest/omrGtestGlue/omrTest.h:38]: This include of `ctype.h` should also be unconditional, and the stale comment (lines 35-38) removed.

**Comment by Deigue** [comment]
@keithc-ca  I made some partial changes, to try and confirm the `ctype.h` change functionality.
However, with the current/latest commit , having the `_AE_BIMODAL` defined at the top of the a2e `ctype.h` header, I am still seeing problems with usages of  `OMR_ISDIGIT()` like earlier :

For reference the full command and errors below:
```bash
cd /jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime/compiler && /xlc210/usr/lpp/IBM/cnw/v2r1/openxl/bin/ibm-clang++64  -D__STDC_LIMIT_MACROS -D_ALL_SOURCE -D_OPEN_THREADS=3 -D_XOPEN_SOURCE=600 -Dj9jit_EXPORTS -DBITVECTOR_BIT_NUMBERING_MSB -DBITVECTOR_64BIT -DBUILD_Z_RUNTIME_INSTRUMENTATION -DCOMPRESS_AOT_DATA -DIBM_ATOE -DIPv6_FUNCTION_SUPPORT -DJ9_PROJECT_SPECIFIC -DJ9VM_TIERED_CODE_CACHE -DJ9ZOS390 -DJ9ZOS39064 -DLONGLONG -DMAXMOVE -DOPENJ9_BUILD -DSUPPORTS_THREAD_LOCAL -DTR_HOST_S390 -DTR_HOST_64BIT -DTR_TARGET_S390 -DTR_TARGET_64BIT -DZOS -fstrict-aliasing -mzos-target=ZOSV2R4 -m64 -O3 -fstack-protector -march=arch10 -std=gnu++14 -fasm -fno-rtti -DYYLMAX=1000 -Wuninitialized -mnocsect   -fvisibility=default -fexec-charset=ISO8859-1 -isystem /jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/cmake/modules/platform/os/../../../../util/a2e/headers -I/usr/lpp/hzc/include -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/compiler/z -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/compiler -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/z -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/thread -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/gc/include -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/compiler/.. -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/codert_vm -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/gc_include -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/gc_glue_java -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/jit_vm -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/nls -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/oti -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/include -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/util -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime/oti -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime/omr -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime/compiler -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/closedj9/runtime/compiler -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core -I/usr/include -I/usr/lpp/cbclib/include -I/include_core -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/closedj9/runtime/include -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime/include -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime/nls -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/util/hashtable/. -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/build/zos-s390x-server-release/vm/runtime/util -I/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/openj9/runtime/util/.  -o CMakeFiles/j9jit.dir/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp.o -c /jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp

//errors:
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:1379:14: error: use of undeclared identifier '__isdigit_a'
 1379 |       while (OMR_ISDIGIT(*option))
      |              ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:3429:20: error: use of undeclared identifier '__isdigit_a'
 3429 |             while (OMR_ISDIGIT(*options))
      |                    ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:3446:23: error: use of undeclared identifier '__isdigit_a'
 3446 |                while (OMR_ISDIGIT(*options))
      |                       ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:4393:14: error: use of undeclared identifier '__isdigit_a'
 4393 |          if (OMR_ISDIGIT(s[0]))
      |              ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:4396:20: error: use of undeclared identifier '__isdigit_a'
 4396 |             while (OMR_ISDIGIT(s[0]))
      |                    ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:4418:14: error: use of undeclared identifier '__isdigit_a'
 4418 |          if (OMR_ISDIGIT(s[0]))
      |              ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:4421:20: error: use of undeclared identifier '__isdigit_a'
 4421 |             while (OMR_ISDIGIT(s[0]))
      |                    ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:4441:14: error: use of undeclared identifier '__isdigit_a'
 4441 |          if (OMR_ISDIGIT(s[0]))
      |              ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)
      |                        ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/compiler/control/OMROptions.cpp:4444:20: error: use of undeclared identifier '__isdigit_a'
 4444 |             while (OMR_ISDIGIT(s[0]))
      |                    ^
/jit/team/gauravc/repos/openj9-openjdk-jdk21-zos/omr/include_core/omrcomp.h:617:24: note: expanded from macro 'OMR_ISDIGIT'
  617 | #define OMR_ISDIGIT(x) __isdigit_a(x)

```

I tried moving around the define of `AE_BIMODAL` itself a bit around in the file itself, but I don't know if that is the problem.
With the current state of the code, there is something that is still making it such that when the macro is encountered, the function isn't defined. 

I am having difficulty finding out why `isdigit_a` is undefined, as the explanation behind the initialization you mentioned yesterday made sense. Is there something else that is prompting the `omrcomp.h` itself to load its contents/usages prior to `ctype.h` itself ?

**Comment by Deigue** [comment]
Made the changes to address the above feedback. Tested with the commandline approach using `-D_AE_BIMODAL` to apply it consistently everywhere and it seems to fix up all the compilation issues that were being seen earlier.

File: cmake/modules/platform/os/zos.cmake [hunk 6]
```diff
@@ -20,6 +20,7 @@
 #############################################################################
 
 list(APPEND OMR_PLATFORM_DEFINITIONS
+	-D_AE_BIMODAL
```
Comment (keithc-ca) [inline cmake/modules/platform/os/zos.cmake:23]: Should this be contributed by `openxl.cmake` instead? Or will this work with `xlc` as well?

File: fvtest/omrGtestGlue/omrTest.h [hunk 7]
```diff
@@ -31,24 +31,9 @@ static int iconv_init_static_variable = iconv_initialization();
 #endif /* defined(J9ZOS390) && !defined(OMR_EBCDIC) */
```
Comment (keithc-ca) [inline fvtest/omrGtestGlue/omrTest.h:33]: Please also delete this blank line (we don't need more than one blank line in a row).

File: util/a2e/headers/ctype.h [hunk 8]
```diff
@@ -33,6 +33,13 @@
  * ===========================================================================
  */
 
+#if !defined(OMR_CTYPE_H)
+#define OMR_CTYPE_H
+
+#if defined(J9ZOS390)
+#define _AE_BIMODAL
+#endif /* defined(J9ZOS390) */
```
Comment (keithc-ca) [inline util/a2e/headers/ctype.h:41]: This is at best redundant (it should be defined by the make system) or may be viewed by the compiler as a redefinition (error).

**Review by keithc-ca — CHANGES_REQUESTED** [review]

File: cmake/modules/platform/os/zos.cmake (hunk 6 above)
Comment (Deigue) [reply cmake/modules/platform/os/zos.cmake:23]: This works with `xlc` as well. I checked this with the compiler team and had to make sure it compiles with both using `AE_BIMODAL` , because after removing the redefinitions from `ctype.h` , it broke the `xlc` builds as well. So adding it here was intentional.

**Comment by Deigue** [comment]
@keithc-ca Both this and https://github.com/eclipse-openj9/openj9/pull/21555 are ready for review, with latest feedback in place/tested.

**Review by keithc-ca — APPROVED** [review]

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
@Deigue Can you look at the failures in the zOS PR build?

**Comment by Deigue** [comment]
I am seeing that bunch of the console output messages earlier were indicative of `OMR_ISDIGIT` not working as planned within `OMROptions.cpp` , where it has multiple usages, and I assume is used by ctest for omr jenkins as well.
Will try to proactively reproduce these errors if I can by attempting a standalone omr zos build with xlc locally, in the past I did see this in one occurence, when `AE_BIMODAL` was not applying correctly to some files.

**Comment by Deigue** [comment]
@babsingh Is there a reason why locally I am only seeing 15 tests with `ctest -V` ?
```
15/15 Test #15: gctest ...........................   Passed    0.43 sec

100% tests passed, 0 tests failed out of 15

Total Test time (real) = 122.40 sec
```
While in the verbose console log these is 28 tests? Is this dependant on the way cmake configures the build at the start?

**Comment by babsingh** [comment]
> While in the verbose console log these is 28 tests? Is this dependant on the way cmake configures the build at the start?

There may be conditional restrictions based on the setup and environment. These can usually be identified by reviewing the test source code and build configuration files.

**Comment by babsingh** [comment]
> Looks like the OMROptions.cpp command/compilation looks ok, so there is something else may be the problem?

Unsure since they are JIT failures. @0xdaryl Is there a JIT member who help @Deigue investigate these?

```
12:23:02  The following tests FAILED:
12:23:02  	  3 - conditionals_example_as_test (Failed)
12:23:02  	  5 - iterfib_example_as_test (Failed)
12:23:02  	  6 - nestedloop_example_as_test (Failed)
12:23:02  	  7 - pow2_example_as_test (Failed)
12:23:02  	  8 - simple_example_as_test (Failed)
12:23:02  	  9 - worklist_example_as_test (Failed)
12:23:02  	 10 - power_example_as_test (Failed)
12:23:02  	 24 - JitBuilderTest (OTHER_FAULT)
12:23:02  	 25 - CompilerTest (OTHER_FAULT)
12:23:02  	 26 - triltest (OTHER_FAULT)
12:23:02  	 27 - comptest (OTHER_FAULT)
12:23:02  	 28 - compunittest (OTHER_FAULT)
```

**Comment by Deigue** [comment]
I was chatting with @Spencer-Comin for some guidance on this,
The way it was running was off locally, so I ran it with the same configure and build commands, and also adding the current build directory to `LIBPATH` to ensure the ctest run afterwards dont error out,
```
cmake -Wdev -C../cmake/caches/Travis.cmake -DCMAKE_C_COMPILER=/bin/c89 -DCMAKE_CXX_COMPILER=/bin/xlc -DOMR_DDR=OFF -DOMR_THR_FORK_SUPPORT=0 ..

make -j4 VERBOSE=1
```

However this has got my build to fail/error before the `eclipse-omr/pr/zos_390_64` build at `compilertest`
```
cd /jit/team/gauravc/repos/xlc/openj9-openjdk-jdk21-zos/omr/build/fvtest/compilertest && /rsusr/openj9_resources/bin/cmake -E cmake_link_script CMakeFiles/compilertest.dir/link.txt --verbose=1
```
Attached linker errors associated with local build:
[linker-compilertest.txt](https://github.com/user-attachments/files/20190323/linker-compilertest.txt)

The full commands look the same.
I was trying to look at the `nm ../../libtestcompiler.a` output, but cannot make sense out of it.

I do have `OMROptions.cpp` compiling with this configure though, and the full command does seem to be good. Wanted to try to get it at the same position as the official eclipse build.
The `<JIT: fatal error: invalid command line> ` originate from `rossa.cpp` in openj9 , that is parsing of the JIT Options ... so I am wondering, @babsingh Do you think the openj9 changes will be needed too? I thought openj9 wouldnt be used at all in terms of jenkins builds.

**Comment by babsingh** [comment]
> The <JIT: fatal error: invalid command line> originate from rossa.cpp in openj9 , that is parsing of the JIT Options ... so I am wondering, @babsingh Do you think the openj9 changes will be needed too?

No, these errors also exist in OMR - see [CompileMethod.cpp](https://github.com/eclipse-omr/omr/blob/master/compiler/control/CompileMethod.cpp).

**Comment by babsingh** [comment]
jenkins build zos(compile:'VERBOSE=1')

**Comment by Deigue** [comment]
Are we good for merging the pair of PR's now, as the builds have passed?

The only change was made to `omrcomp.h` as below:
```
#if defined(J9ZOS390) && !defined(OMR_EBCDIC)
```

I added the `!defined(OMR_EBCDIC)` , as this was the reason why the OMR only builds were failing. With OMR standalone, the builds were running in EBCDIC mode, and in these scenarios it should not be using the ascii version, i.e. `isdigit_a()` 

The extension repos compilation along with OMR/OpenJ9 remains to be fine.

**Comment by babsingh** [comment]
jenkins build all

**Review by babsingh — APPROVED** [review]
