### ISSUE TITLE
TestJitBuilderAPIGenerator failure: no attribute assertRegexpMatches

### ISSUE THREAD

**Issue by babsingh** [eclipse-omr/omr#7181]
> https://dev.azure.com/eclipse-omr/ea4519db-b27e-4d19-a971-f01491f803e3/_apis/build/builds/8241/logs/67

```
2023-11-10T22:20:05.5840210Z 2: ..................................................................................................E...EEEEEEEEEEEEEEEE.............EE.EEsEEsEEs...
2023-11-10T22:20:05.5841430Z 2: ======================================================================
2023-11-10T22:20:05.5842770Z 2: ERROR: test_generate_allocator_decl_1 (test.cppgentests.CppGeneratorTest.test_generate_allocator_decl_1)
2023-11-10T22:20:05.5844840Z 2: ----------------------------------------------------------------------
2023-11-10T22:20:05.5845760Z 2: Traceback (most recent call last):
2023-11-10T22:20:05.5847120Z 2:   File "/Users/runner/work/1/s/jitbuilder/apigen/test/cppgentests.py", line 245, in test_generate_allocator_decl_1
2023-11-10T22:20:05.5848850Z 2:     self.assertRegexpMatches(self.generator.generate_allocator_decl(class_desc),
2023-11-10T22:20:05.5850090Z 2:     ^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T22:20:05.5851190Z 2: AttributeError: 'CppGeneratorTest' object has no attribute 'assertRegexpMatches'
2023-11-10T22:20:05.5852180Z 2: 

...

2023-11-10T22:20:05.6070130Z 2: FAILED (errors=25, skipped=3)
2023-11-10T22:20:05.6070920Z 2: warning: The package 'jsonschema' is not installed so certain tests will be skipped
2023-11-10T22:20:05.6072030Z 32/49 Test  #2: TestJitBuilderAPIGenerator ..........***Failed    0.94 sec
```

**Comment by babsingh** [comment]
In my quick scan of the previous PR builds (https://dev.azure.com/eclipse-omr/omr/_build?definitionId=1&_a=summary), I found that the failure is also seen in https://github.com/eclipse/omr/pull/7046. fyi @hzongaro @jdmpapin

**Comment by hzongaro** [comment]
In a [build](https://dev.azure.com/eclipse-omr/omr/_build/results?buildId=8217&view=logs&j=aa2fd561-a338-5537-45ee-49ae22aea958&t=20ff6471-47a7-5631-6842-540dac3e3fb4) I found where that test passed, I see this:

```
7: Working Directory: /Users/runner/work/1/s/build/jitbuilder/release
27: Test timeout computed to be: 10000000
2: ................................................................................................../Users/runner/work/1/s/jitbuilder/apigen/test/cppgentests.py:245: DeprecationWarning: Please use assertRegex instead.
2:   self.assertRegexpMatches(self.generator.generate_allocator_decl(class_desc),
```

**Comment by babsingh** [comment]
In the Azure pipeline, [macOS-latest](https://github.com/eclipse/omr/blob/10bcf8f56e9952a06a599a303ddf1d68ee3bfa8f/azure-pipelines.yml#L196) is used for the VM image, which probably has the **latest Python version** where `assertRegexpMatches` no longer exists. If JitBuilder has a specific Python version requirement, then it can be included in [azure-pipelines.yml](https://github.com/eclipse/omr/blob/10bcf8f56e9952a06a599a303ddf1d68ee3bfa8f/azure-pipelines.yml#L196). fyi @AdamBrousseau
